CREATE TABLE article (
  code VARCHAR(50) NOT NULL,
  description VARCHAR(128) NOT NULL,
  PRIMARY KEY (code)
);

CREATE TABLE rule (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(128) NOT NULL UNIQUE,
  rank INT NOT NULL
);

CREATE TABLE rule_input_article (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  rule_id BIGINT NOT NULL,
  code VARCHAR(50) NOT NULL,
  description VARCHAR(128) NOT NULL,
  amount INT NOT NULL,
  in_catalogue BOOLEAN NOT NULL,
  UNIQUE (rule_id, code),
  FOREIGN KEY (rule_id) REFERENCES rule (id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE rule_output_article (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  rule_id BIGINT NOT NULL,
  code VARCHAR(50) NOT NULL,
  description VARCHAR(128) NOT NULL,
  amount INT NOT NULL,
  in_catalogue BOOLEAN NOT NULL,
  UNIQUE (rule_id, code),
  FOREIGN KEY (rule_id) REFERENCES rule (id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE parameter (
  id VARCHAR2(128) NOT NULL,
  value VARCHAR2(1024) NOT NULL,
  PRIMARY KEY (id)
);